### PR TITLE
Adopt go modules

### PR DESCRIPTION
**Pull request by rmfitzpatrick**
In an attempt to satisfy https://github.com/soheilhy/cmux/issues/70 these changes adopt go modules and move the example content to a new `github.com/soheily/cmux/example`* module.

### CODE REVIEW

**Comment by ptabor** [comment]
Please merge this change. 

It's significant problem for etcd that, fact that we depend of cmux is breaking us additional dependencies, 
in particular:  google.golang.org/grpc/examples/helloworld/helloworld, that transitively brings unwented version of grpc or protos.

**Comment by ptabor** [comment]
@soheilhy Could you, please, comment on perspectives to have it merged (or in different way isolate transitive dependencies coming from the example) ?

**Comment by soheilhy** [comment]
Happy to merge this. @rmfitzpatrick can you please rebase and resolve the conflict?

**Comment by rmfitzpatrick** [comment]
@soheilhy, updated, thanks for your patience and review.

**Pull request merged**
