### PR TITLE
`go tool vet --shadow .`

### PR DESCRIPTION
**Pull request by tamird**
@soheilhy this is a more palatable version of the earlier proposal of this lint. Figured I'd send the PR since you already have to review #17 :)

### CODE REVIEW

**Comment by soheilhy** [comment]
LGTM, Thanks!

**Comment by shurcooL** [comment]
IMO the change in this PR did not make the code more readable, but less so. Do you agree, and do you think it was worth making?

**Comment by shurcooL** [comment]
As alternatives, you could do one of:

1. Change `if err := r.Body.Close(); err != nil {` to `if err = r.Body.Close(); err != nil {` in order to resolve the vet warning.

2. Change `if err := r.Body.Close(); err != nil {` to `if err1 := r.Body.Close(); err1 != nil {` in order to resolve the vet warning.

3. Don't use -shadow flag in CI, instead run it occasionally in a local setup and see if any warnings it emits are real problems.

**Comment by soheilhy** [comment]
Yes, I agree and that's my preferred way. I pondered upon this one. 

Having said that, I'd prefer to keep the "-shadow" flag. I'll fix and will send a pr.

**Pull request merged**
