### PR TITLE
TeeReader already doesn't use allocation

### PR DESCRIPTION
**Pull request by puellanivis**
So, optimizing this code is mostly just a chance to introduce bugs.

Clean this up a bit and voila, this should work basically the same.

### CODE REVIEW

**Comment by puellanivis** [comment]
Let me know how this code looks. I'm definitely sticking my nose in here without knowing exactly what this `bufferedReader` is supposed to be doing, and what it's used for.

So, I did keep all the functionality the same.

**Comment by soheilhy** [comment]
cmux was originally based on TeeReader and there is too much hidden cost to it:
https://github.com/soheilhy/cmux/commit/59b6f01712cb9b4173fc8fd88fadb17cda0a691c

So, I won't accept/merge this PR.

**Comment by puellanivis** [comment]
```
gloss cmux$  go test -bench . -benchmem
PASS
BenchmarkCMuxConnHTTP1-24        1000000              1049 ns/op             280 B/op          4 allocs/op
BenchmarkCMuxConnHTTP2-24        1000000              1077 ns/op             304 B/op          4 allocs/op
BenchmarkCMuxConnHTTP1n2-24      1000000              1245 ns/op             312 B/op          5 allocs/op
BenchmarkCMuxConnHTTP2n1-24      1000000              1226 ns/op             312 B/op          5 allocs/op
ok      github.com/soheilhy/cmux        5.250s
[master|✓]
gloss cmux$ go test -bench . -benchmem
PASS
BenchmarkCMuxConnHTTP1-24        1000000              1064 ns/op             280 B/op          4 allocs/op
BenchmarkCMuxConnHTTP2-24        1000000              1065 ns/op             304 B/op          4 allocs/op
BenchmarkCMuxConnHTTP1n2-24      1000000              1156 ns/op             312 B/op          5 allocs/op
BenchmarkCMuxConnHTTP2n1-24      1000000              1157 ns/op             312 B/op          5 allocs/op
ok      github.com/soheilhy/cmux        5.052s
[master|✓]
gloss cmux$ go test -bench . -benchmem
PASS
BenchmarkCMuxConnHTTP1-24        1000000              1062 ns/op             280 B/op          4 allocs/op
BenchmarkCMuxConnHTTP2-24        1000000              1181 ns/op             304 B/op          4 allocs/op
BenchmarkCMuxConnHTTP1n2-24      1000000              1222 ns/op             312 B/op          5 allocs/op
BenchmarkCMuxConnHTTP2n1-24      1000000              1228 ns/op             312 B/op          5 allocs/op
ok      github.com/soheilhy/cmux        5.307s
[master|✓]
gloss cmux$ go test -bench . -benchmem
PASS
BenchmarkCMuxConnHTTP1-24        1000000              1036 ns/op             280 B/op          4 allocs/op
BenchmarkCMuxConnHTTP2-24        1000000              1092 ns/op             304 B/op          4 allocs/op
BenchmarkCMuxConnHTTP1n2-24      1000000              1221 ns/op             312 B/op          5 allocs/op
BenchmarkCMuxConnHTTP2n1-24      1000000              1245 ns/op             312 B/op          5 allocs/op
ok      github.com/soheilhy/cmux        5.150s
```

```
gloss cmux$ !go
go test -bench . -benchmem
PASS
BenchmarkCMuxConnHTTP1-24        1000000              1045 ns/op             312 B/op          5 allocs/op
BenchmarkCMuxConnHTTP2-24        1000000              1086 ns/op             336 B/op          5 allocs/op
BenchmarkCMuxConnHTTP1n2-24      1000000              1151 ns/op             344 B/op          6 allocs/op
BenchmarkCMuxConnHTTP2n1-24      1000000              1153 ns/op             344 B/op          6 allocs/op
ok      _/home/snowgirl/Work/puellanivis/cmux   5.029s
[master|∆1]
gloss cmux$ !go
go test -bench . -benchmem
PASS
BenchmarkCMuxConnHTTP1-24        1000000              1083 ns/op             312 B/op          5 allocs/op
BenchmarkCMuxConnHTTP2-24        1000000              1075 ns/op             336 B/op          5 allocs/op
BenchmarkCMuxConnHTTP1n2-24      1000000              1132 ns/op             344 B/op          6 allocs/op
BenchmarkCMuxConnHTTP2n1-24      1000000              1151 ns/op             344 B/op          6 allocs/op
ok      _/home/snowgirl/Work/puellanivis/cmux   5.025s
[master|∆1]
gloss cmux$ go test -bench . -benchmem
PASS
BenchmarkCMuxConnHTTP1-24        1000000              1162 ns/op             312 B/op          5 allocs/op
BenchmarkCMuxConnHTTP2-24        1000000              1057 ns/op             336 B/op          5 allocs/op
BenchmarkCMuxConnHTTP1n2-24      1000000              1236 ns/op             344 B/op          6 allocs/op
BenchmarkCMuxConnHTTP2n1-24      1000000              1265 ns/op             344 B/op          6 allocs/op
ok      _/home/snowgirl/Work/puellanivis/cmux   5.302s
[master|∆1]
gloss cmux$ go test -bench . -benchmem
PASS
BenchmarkCMuxConnHTTP1-24        1000000              1176 ns/op             312 B/op          5 allocs/op
BenchmarkCMuxConnHTTP2-24        1000000              1096 ns/op             336 B/op          5 allocs/op
BenchmarkCMuxConnHTTP1n2-24      1000000              1237 ns/op             344 B/op          6 allocs/op
BenchmarkCMuxConnHTTP2n1-24      1000000              1268 ns/op             344 B/op          6 allocs/op
ok      _/home/snowgirl/Work/puellanivis/cmux   5.353s
```

`io.TeeReader` works fine. `io.MultiReader` were the complicating factor in the naïve implementation, as well as `bytes.Reader`/`bytes.Buffer`. Both of which have some statistically significant overhead to their reading.

The statistical outliers are a result of gc running.

I'm not suggesting you need take this code, I'm just making some suggestions. (I know you did a big change after I started working from my fork.)

**Comment by puellanivis** [comment]
Cool cool. :) It honestly took me like nearly a whole day to get the code into a decent state there, and I'm like, “this is totally throw away code anyways.”

It would be nice if there were a more “pure” bytes.Buffer… like why doesn't it support seeking, but does support unreading, and that stuff? That would make the code here a lot more simple…

Then just build the more complex stuff on top of the purer code? … meh. I have weird entertainment interests… I could have been playing Terraria that whole time, rather than doing “example” code… >_<

**Comment by soheilhy** [comment]
Thanks for the effort and the code. But, yeah, given the limits in the API, it's really difficult to simplify this part of the code. Having said that, any PR to lower the allocation is appreciated.

**Comment by puellanivis** [comment]
Yeah, I've noticed a few holes in the standard library, and have written my own library functions to cover them.

Having a straight up raw bare-bones buffer without unreads, etc, would be nice. As would a buffering pipe… (I hate opening up a file descriptor to an OS pipe to get some functionality that I ought be able to do entirely within memory…)

**Pull request closed without merging**
