### PR TITLE
Fix memory growth

### PR DESCRIPTION
**Pull request by soheilhy**

### CODE REVIEW

**Comment by soheilhy** [comment]
Yeah, thanks for the note. it's fixed the new version.

**Comment by puellanivis** [comment]
Hm… weird, it doesn't show up as fixed? The commit `bf4a8ed` seems to still be using `s.buffer.Cap()` o.O

**Comment by soheilhy** [comment]
The change is to use `s.buffer.Cap() != 0` instead of `s.buffer.Cap() == 0`, as the criteria to release the buffer. What's your objection?

**Comment by puellanivis** [comment]
My objection seems to by my poor reading skills. Withdrawn. :)

**Pull request merged**
